### ISSUE TITLE
Cannot install package from repository

### ISSUE THREAD

**Issue by kapulkin** [yandex-cloud/ydb-python-sdk#6]
`
pip3 install git+https://github.com/yandex-cloud/ydb-python-sdk
`
gives error with log

`
bash-3.2$ python3 -m pip install git+https://github.com/yandex-cloud/ydb-python-sdk.git@48b2d16d09e2b54099a425452f8238ad32a00363
Collecting git+https://github.com/yandex-cloud/ydb-python-sdk.git@48b2d16d09e2b54099a425452f8238ad32a00363
  Cloning https://github.com/yandex-cloud/ydb-python-sdk.git (to revision 48b2d16d09e2b54099a425452f8238ad32a00363) to /private/tmp/pip-req-build-jc3kdlcg
    ERROR: Command errored out with exit status 1:
     command: /Library/Frameworks/Python.framework/Versions/3.8/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/tmp/pip-req-build-jc3kdlcg/setup.py'"'"'; __file__='"'"'/private/tmp/pip-req-build-jc3kdlcg/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /private/tmp/pip-pip-egg-info-7fe_9pja
         cwd: /private/tmp/pip-req-build-jc3kdlcg/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/tmp/pip-req-build-jc3kdlcg/setup.py", line 5, in <module>
        with open('VERSION', 'r') as r:
    FileNotFoundError: [Errno 2] No such file or directory: 'VERSION'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
`

I suppose, you need to add VERSION file in the repo root.

**Comment by ZooKeeper** [comment]
Sorry for the late reply. I can't replicate the issue at the moment. Looks like it has been resolved
